function verex(){exemplarSANT=this.getAttribute("ex").replace(".","_")+"_#/1";window.open("https://www.usc.gal/herbario/?"+exemplarSANT,"_blank")}document.querySelectorAll(".exe").forEach(function(a){a.onclick=verex;cl=a.className;a.title="Centuria "+cl.split("c_")[1].split(" ")[0];a.title+=", N\u00ba"+a.id;a.title+=",\n (herbario "+cl.split(" ")[cl.split(" ").length-1]+")";a.title+="\n Zona: "+cl.split("z_")[1].split(" ")[0]});
function escapeRegExp(a){return a.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}function replaceAll(a,b,c){return a.replace(new RegExp(escapeRegExp(b),"g"),c)}
function verold(a,b,c){document.getElementById("panel").style.visibility="visible";fotos=a.split("#");rollohtml="";server="193.144.34.193/iipsrv/iipsrv.fcgi?fif=/mnt/scratch/pyrtif/";wid="300";sampleimaxe="bc_SANT_201504_C/20150430_044.pyr.tif";for(i=0;i<fotos.length;i++)fsplit=fotos[i].split("|"),scale=fsplit[3]/25.4,thumb="https://images.weserv.nl/?url="+replaceAll(replaceAll(server+fsplit[1]+"/"+fsplit[2]+"&CNT=1.1&WID="+wid+"&CVT=jpeg","?","%3F"),"&","%26"),big="https://images.weserv.nl/?url="+
replaceAll(replaceAll(server+fsplit[1]+"/"+fsplit[2]+"&CNT=1.1&WID=1100&CVT=jpeg","?","%3F"),"&","%26"),url="https://herbarios.ga/imsrv/visorcesga.php?fif="+fsplit[1]+"/"+fsplit[2]+"&scale="+scale,rollohtml+="<a href="+url+" target=_blank><img class='imaxe' src='"+thumb+"'></a> ";urlsant="https://www.usc.es/herbario/"+b+"/"+c;document.getElementById("visor").innerHTML="<h1><a href='"+urlsant+"' target=_blank>"+b+" "+c+"</a></h1><pre>"+fotos+"</pre><hr>"+rollohtml}
function verdatosex(a,b){return""}function v(a){ex=a.getAttribute("ex");exr=ex.replace(".","/");exr=ex.replace(".","_")+"_#/1";alert(a.id+": "+ex+" = "+exr);window.open("https://www.usc.es/herbario/?"+exr,"_blank")}
function ver(a,b,c){document.getElementById("panel").style.visibility="visible";fotos=a.split("#");rollohtml="";ex=document.querySelector('[ex="'+b+"."+c+'"]');dj=JSON.parse(ex.getAttribute("data-json"));rollohtml+="<div class='label'>";rollohtml+="<span class='label_exsic'><b>"+dj.h+"</b>";rollohtml+=". Centuria "+dj.c+", N\u00ba"+dj.n+" ("+(parseInt(dj.c)+1995).toString()+"):</span>";rollohtml+="\x3c!--br--\x3e<div id='div_taxon'><span class='label_taxon'><i>"+dj.sci+"</i></span></div>";rollohtml+=
"\x3c!--br--\x3e<span class='campo'><i>Legit</i>:</span> "+dj.leg+"</i> ["+dj.ano+"/"+dj.mes+"/"+dj.dia+"]";rollohtml+="<br><span class='campo'>Lugar:</span> "+dj.loc;rollohtml+="<br><span class='campo'>Habitat:</span> "+dj.hab;rollohtml+="<br></div><hr>";server="193.144.34.193/iipsrv/iipsrv.fcgi?fif=/mnt/scratch/pyrtif/";wid="200";sampleimaxe="bc_SANT_201504_C/20150430_044.pyr.tif";if(0<a.length)for(i=0;i<fotos.length;i++)fsplit=fotos[i].split("|"),scale=fsplit[3]/25.4,protocol="https",protocol=
"http",thumb=protocol+"://images.weserv.nl/?url="+replaceAll(replaceAll(server+fsplit[1]+"/"+fsplit[2]+"&CNT=1.1&WID="+wid+"&CVT=jpeg","?","%3F"),"&","%26"),big=protocol+"://images.weserv.nl/?url="+replaceAll(replaceAll(server+fsplit[1]+"/"+fsplit[2]+"&CNT=1.1&WID=1100&CVT=jpeg","?","%3F"),"&","%26"),url="https://herbarios.ga/imsrv/visorcesga.php?fif="+fsplit[1]+"/"+fsplit[2]+"&scale="+scale,rollohtml+="<a onclick=\"verdetalle('"+a+"','"+b+"','"+c+"','"+url+"');\"><img class='imaxe' src='"+thumb+
"'></a> ";else rollohtml+="<h1>DIXITALIZACI\u00d3N PENDENTE</h1>";urlsant="https://www.usc.es/herbario/"+b+"/"+c;back="<button onclick=\"ver('"+fotos+"','"+b+"','"+c+'\');" title="ATR\u00c1S">&lt;&lt;&lt;</button>';back="";datosex=verdatosex(b,c);linksant="<a href='"+urlsant+"' target=_blank title='ver datos en web Herbario SANT'>"+b+" "+c+"</a>";document.getElementById("visor").innerHTML="<h3>"+back+" "+linksant+"</h3>"+datosex+rollohtml}
function verdetalle(a,b,c,d){back="<button onclick=\"ver('"+a+"','"+b+"','"+c+'\');" title="ATR\u00c1S">&lt;&lt;&nbsp;etiqueta</button>';urlsant="https://www.usc.es/herbario/"+b+"/"+c;linksant="<a href='"+urlsant+"' target=_blank title='ver datos en web Herbario SANT'>"+b+" "+c+"</a>";document.getElementById("visor").innerHTML="<h3>"+back+" "+linksant+"</h3><iframe style='width:100%;height:90%;' src='"+d+"'></iframe>"}
var readJson=function(a,b){fs.readFile(require.resolve(a),function(a,d){a?b(a):b(null,JSON.parse(d))})};
function filtrar(){classtotal=".exe";exs=document.querySelectorAll(classtotal);for(i=0;i<exs.length;i++)exs[i].style.display="none";selc=document.getElementById("sel_centuria");classc=selc[selc.selectedIndex].value;""<classc&&(classtotal+="."+classc);selz=document.getElementById("sel_zona");classz=selz[selz.selectedIndex].value;""<classz&&(classtotal+="."+classz);selh=document.getElementById("sel_herbario");classh=selh[selh.selectedIndex].value;""<classh&&(classtotal+="."+classh);console.log(classtotal);
exs=document.querySelectorAll(classtotal);utax=ux="";for(i=0;i<exs.length;i++)exs[i].style.display="inline",nx=exs[i].textContent.split(" ")[0],tax=exs[i].getAttribute("t"),x=tax.split(" ")[0],resto=tax.split(" "),resto.shift(),sep=0<i?", ":"",x[0]!=ux[0]&&(sep="<br><br>"),x!=ux?(exs[i].innerHTML=sep+"<i><b>"+x+"</b> "+resto.join(" ")+"</i>",ux=x+""):exs[i].innerHTML=tax!=utax?sep+"<i>"+x[0]+"."+resto.join(" ")+"</i>":" (+)",utax=tax+""}
function cancel_sel(){document.getElementById("sel_herbario").selectedIndex=0;document.getElementById("sel_centuria").selectedIndex=0;document.getElementById("sel_zona").selectedIndex=0;filtrar()}document.getElementById("sel_herbario").addEventListener("change",filtrar);document.getElementById("sel_centuria").addEventListener("change",filtrar);document.getElementById("sel_zona").addEventListener("change",filtrar);document.getElementById("cancel_sel").addEventListener("click",cancel_sel);filtrar();
function myFunction1(){var a=document.getElementById("fname");a.value=a.value.toUpperCase()}function myFunction(){var a,b;var c=document.getElementById("myInput").value.toUpperCase();var d=document.getElementById("myTable").getElementsByTagName("tr");for(b=0;b<d.length;b++)if(a=d[b].getElementsByTagName("td")[0])a=a.textContent||a.innerText,-1<a.toUpperCase().indexOf(c)?d[b].style.display="":d[b].style.display="none"}filterSelection("all");
function filterSelection(a){var b;var c=document.getElementsByClassName("filterDiv");"all"==a&&(a="");for(b=0;b<c.length;b++)w3RemoveClass(c[b],"show"),-1<c[b].className.indexOf(a)&&w3AddClass(c[b],"show")}function w3AddClass(a,b){var c=a.className.split(" ");var d=b.split(" ");for(b=0;b<d.length;b++)-1==c.indexOf(d[b])&&(a.className+=" "+d[b])}
function w3RemoveClass(a,b){var c=a.className.split(" ");var d=b.split(" ");for(b=0;b<d.length;b++)for(;-1<c.indexOf(d[b]);)c.splice(c.indexOf(d[b]),1);a.className=c.join(" ")};
